version: '2'
services:
    weareholidays-app:
        image: weareholidays
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://weareholidays-postgresql:5432/weareholidays
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    weareholidays-postgresql:
        extends:
            file: postgresql.yml
            service: weareholidays-postgresql
